<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>ru.mfilatov</groupId>
  <artifactId>kafka-test-client-parent</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>
  
  <modules>
    <module>kafka-test-client-lib</module>
    <module>kafka-test-client-service</module>
  </modules>

  <properties>
        <!-- Build Settings -->
        <java.version>24</java.version>
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <maven.compiler.proc>full</maven.compiler.proc>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Dependency Versions -->
        <spring-boot.version>3.4.5</spring-boot.version>
        <lombok.version>1.18.38</lombok.version>
        <logback.version>1.5.18</logback.version>
        <junit.version>5.12.2</junit.version>
        <junit-platform.version>1.12.2</junit-platform.version>
        <assertj.version>3.27.3</assertj.version>
        <kafka.version>4.0.0</kafka.version>
        <awaitility.version>4.3.0</awaitility.version>
        <testcontainers.version>1.21.0</testcontainers.version>
        <junit-pioneer.version>2.3.0</junit-pioneer.version>

        <!-- Plugin Versions -->
        <compiler.version>3.14.0</compiler.version>
        <surefire.version>3.5.3</surefire.version>
        <spotless.version>2.44.4</spotless.version>
    </properties>


    <build>
        <plugins>
            <!-- Spotless (Code Formatting) -->
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>${spotless.version}</version>
                <configuration>
                    <java>
                        <cleanthat />
                        <googleJavaFormat />
                        <removeUnusedImports />
                        <formatAnnotations />

                        <licenseHeader>
                            <content>
/*
* Copyright 2025 Mikhail Filatov
* SPDX-License-Identifier: Apache-2.0
*/
                            </content>
                        </licenseHeader>

                        <includes>
                            <include>src/**/*.java</include>
                        </includes>

                        <excludes>
                            <exclude>**/target/**</exclude>
                            <exclude>**/generated/**</exclude>
                        </excludes>
                    </java>
                </configuration>
            </plugin>
        </plugins>
    </build>
  
</project>